Add HertzBeat to Monitoring
n1trux/awesome-sysadmin pull request #417
Opened 2022-10-19 01:21 UTC by tomsun28

### Application name / category

[HertzBeat](https://github.com/dromara/hertzbeat) / Monitoring

### Source URL 

https://github.com/dromara/hertzbeat

### Why it is awesome

HertzBeat is an open source, real-time monitoring system with custom-monitor and agentless. Support web service, database, os, middleware and more. Popular in [reddit](https://www.reddit.com/r/selfhosted/comments/wsw124/hertzbeat_an_opensource_monitoring_system_with/).

2023-03-01 13:33 UTC, nodiscc requested changes, later dismissed
Hi @tomsun28 , since https://github.com/awesome-foss/awesome-sysadmin/pull/459 we have new contribution guidelines in place, could you please take some time to answer the following questions as best you can? Thanks

- **Why is it awesome?**
- **Have you used it? For how long?**
- **Is this in a personal or professional setup?**
- **How many devices/users/services/... do you manage with it?**
- **Biggest pros/cons compared to other solutions?**

2023-09-24 11:04 UTC, Rabenherz112 requested changes
Made small changes to the Description and following the [Documentation](https://hertzbeat.dromara.org/docs/) the Application can also be installed via Docker and Kubernetes.

2023-09-24 11:04 UTC, Rabenherz112 commented on README.md
> +- [HertzBeat](https://github.com/dromara/hertzbeat) - An open-source real-time monitoring system with custom-monitor and agentless. `Apache-2.0` `Java`
```suggestion
- [HertzBeat](https://hertzbeat.dromara.org/) - Real-time monitoring system with custom-monitor and agentless. ([Source Code](https://github.com/dromara/hertzbeat)) `Apache-2.0` `Java/Docker/K8S`
```

2023-09-24 11:38 UTC, tomsun28 commented on README.md
> +- [HertzBeat](https://github.com/dromara/hertzbeat) - An open-source real-time monitoring system with custom-monitor and agentless. `Apache-2.0` `Java`
thanks👍

2023-09-24 11:40 UTC, tomsun28 commented
> Made small changes to the Description and following the [Documentation](https://hertzbeat.dromara.org/docs/) the Application can also be installed via Docker and Kubernetes.

thanks. 👍 the change has apply.

2023-09-24 12:01 UTC, Rabenherz112 approved these changes

2023-10-08 09:20 UTC, Rabenherz112 commented
/cc @nodiscc

2024-01-02 07:27 UTC, tomsun28 commented
@nodiscc hi, happy new year. how about this pr?

2024-06-29 10:59 UTC, vorwd approved these changes
These changes look good from my end -- but I don't have approval rights :+1:

2025-09-15 20:22 UTC, nodiscc requested changes

2025-09-16 17:14 UTC, tomsun28 commented
hi @nodiscc Thanks for helping update the description, the readme.md has updated.

2025-10-15 11:06 UTC, nodiscc approved these changes

2026-06-19 21:17 UTC, Rabenherz112 commented
Thanks for your contribution!

We've migrated all contributions over to a new repository: **[awesome-foss/awesome-sysadmin-data](https://github.com/awesome-foss/awesome-sysadmin-data)**. This repo no longer accepts software additions directly.

Please resubmit your software over at the new repo.

Closing this PR for now, sorry for the extra step, and thanks for understanding!

2026-06-19 21:17 UTC, closed without merging