SSO PWM
n1trux/awesome-sysadmin pull request #419
Opened 2022-10-19 21:48 UTC by darkdragon-001

Thank you for taking the time to work on a PR for Awesome-Sysadmin!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software)
- [x] Software your are submitting is not your own, unless you have a healthy ecosystem with a few contributors (which aren't your sock puppet accounts).
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 80 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at [awesome-selfhosted](https://github.com/awesome-foss/awesome-sysadmin)
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-foss/awesome-sysadmin/issues) or [PRs](https://github.com/awesome-foss/awesome-sysadmin/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items (see #409)
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

--------------

### Why it is awesome

This provider is so awesome because it allows you to maintain a single account but provide many independent services.

2023-03-01 13:34 UTC, nodiscc requested changes
Hi @darkdragon-001 , since https://github.com/awesome-foss/awesome-sysadmin/pull/459 we have new contribution guidelines in place, could you please take some time to answer the following questions as best you can? Thanks

- **Why is it awesome?**
- **Have you used it? For how long?**
- **Is this in a personal or professional setup?**
- **How many devices/users/services/... do you manage with it?**
- **Biggest pros/cons compared to other solutions?**

2023-03-05 19:40 UTC, darkdragon-001 commented
**Why is it awesome?**
- extends established and stable applications (LDAP) with self-service to reduce support capacities
- adds SSO interfaces to easily connect with other applications

**Have you used it? For how long?**
I tried it shortly but I then have been overvoted to go with a proprietary setup :sob: 

**Is this in a personal or professional setup?**
Organization of volunteers.

**How many devices/users/services/... do you manage with it?**
Several thousands.

**Biggest pros/cons compared to other solutions?**
Pro: Clean and fast building on top of existing and established software
Con: Less widespread than more established alternatives

2023-03-06 12:29 UTC, nodiscc reviewed
Thanks. Waiting for additional reviewers

2023-09-24 11:19 UTC, Rabenherz112 reviewed
I'm not entirely convinced that this should be included in the list. Firstly, it appears that you may not have extensive experience with it yourself. Additionally, when I review [the issue tab](https://github.com/pwm-project/pwm/issues), it seems that there are numerous unresolved issues, and the application receives only minor updates, mainly related to dependency updates.

2023-09-24 11:29 UTC, darkdragon-001 commented
I do see regular commits including bug fixes and huge refactorings in the commit history: https://github.com/pwm-project/pwm/commits/master.

To me it seems like the project already has a lot of great features. If people want additional features they are encouraged to send a PR with such addition and the maintainer seems very open to integrate proposed changes. Of course just opening an issue does not give any guarantee that someone else will work on it in their free time without any sort of reward.

2023-09-24 12:00 UTC, Rabenherz112 commented
I share your perspective that the application appears to be quite mature and doesn't require as much maintenance as some other applications.

However, it does strike me as somewhat unusual that there are numerous open issues dating all the way back to 2016. That's why I am a bit unsure about it. I wholeheartedly agree that opening issues doesn't guarantee that they will be fixed or implemented, but there seems to be a limited response from the main maintainer regarding such issues. Additionally, certain issues appear to have been open for multiple years without any response, such as [#57](https://github.com/pwm-project/pwm/issues/57), [#536](https://github.com/pwm-project/pwm/issues/536), and several others (though I'm uncertain if this might be attributable to user errors).

2026-06-19 21:17 UTC, Rabenherz112 commented
Thanks for your contribution!

We've migrated all contributions over to a new repository: **[awesome-foss/awesome-sysadmin-data](https://github.com/awesome-foss/awesome-sysadmin-data)**. This repo no longer accepts software additions directly.

Please resubmit your software over at the new repo.

Closing this PR for now, sorry for the extra step, and thanks for understanding!

2026-06-19 21:17 UTC, closed without merging