SSO Kratos
n1trux/awesome-sysadmin pull request #420
Opened 2022-10-19 21:48 UTC by darkdragon-001

Thank you for taking the time to work on a PR for Awesome-Sysadmin!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software)
- [x] Software your are submitting is not your own, unless you have a healthy ecosystem with a few contributors (which aren't your sock puppet accounts).
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 80 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at [awesome-selfhosted](https://github.com/awesome-foss/awesome-sysadmin)
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-foss/awesome-sysadmin/issues) or [PRs](https://github.com/awesome-foss/awesome-sysadmin/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items (see #409)
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

--------------

### Why it is awesome

This provider is so awesome because it allows you to maintain a single account but provide many independent services.

2023-03-01 13:34 UTC, nodiscc requested changes
Hi @darkdragon-001 , since https://github.com/awesome-foss/awesome-sysadmin/pull/459 we have new contribution guidelines in place, could you please take some time to answer the following questions as best you can? Thanks

- **Why is it awesome?**
- **Have you used it? For how long?**
- **Is this in a personal or professional setup?**
- **How many devices/users/services/... do you manage with it?**
- **Biggest pros/cons compared to other solutions?**

2023-03-05 19:37 UTC, darkdragon-001 commented
**Why is it awesome?**
- Fast and future-proof written in Golang.
- Ory-hardened authentication
- MFA
- FIDO2
- profile management
- identity schemas
- social sign in
- registration
- account recovery
- IoT authentification

**Have you used it? For how long?**
I tried it shortly but I then have been overvoted to go with a proprietary setup :sob: 

**Is this in a personal or professional setup?**
Organization of volunteers.

**How many devices/users/services/... do you manage with it?**
Several thousands.

**Biggest pros/cons compared to other solutions?**
Pro: Modern, clean, future-proof, secure
Con: Less widespread than more established alternatives

2023-03-06 12:27 UTC, nodiscc reviewed
Thanks. Waiting for additional reviewers

2023-07-06 16:45 UTC, nodiscc requested changes

2023-07-06 16:45 UTC, nodiscc commented on README.md
> +- [Kratos](https://www.ory.sh/kratos/) - Next-gen identity server with Ory-hardened authentication, MFA, FIDO2, profile management, identity schemas, social sign in, registration, account recovery, a
```suggestion
- [Kratos](https://www.ory.sh/kratos/) - Next-gen identity server with Ory-hardened authentication, MFA, FIDO2, profile management, identity schemas, social sign in, registration, account recovery, and IoT auth. Golang, headless, API-only - without templating or theming headaches. ([Source Code](https://github.com/ory/kratos)) `Apache-2.0` `Golang`
```

2026-06-19 21:17 UTC, Rabenherz112 commented
Thanks for your contribution!

We've migrated all contributions over to a new repository: **[awesome-foss/awesome-sysadmin-data](https://github.com/awesome-foss/awesome-sysadmin-data)**. This repo no longer accepts software additions directly.

Please resubmit your software over at the new repo.

Closing this PR for now, sorry for the extra step, and thanks for understanding!

2026-06-19 21:17 UTC, closed without merging