Added Kopia to Backups
n1trux/awesome-sysadmin pull request #429
Opened 2022-12-11 10:46 UTC by martinge17

Thank you for taking the time to work on a PR for Awesome-Sysadmin!

To ensure your PR is dealt with swiftly please check the following:

- [X] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software)
- [X] Software your are submitting is not your own, unless you have a healthy ecosystem with a few contributors (which aren't your sock puppet accounts).
- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 80 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [X] Additions are inserted preserving alphabetical order.
- [X] Additions are not already listed at [awesome-selfhosted](https://github.com/awesome-foss/awesome-sysadmin)
- [X] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-foss/awesome-sysadmin/issues) or [PRs](https://github.com/awesome-foss/awesome-sysadmin/pulls), including closed ones.
- [X] Any category you are creating has the minimum requirement of 3 items.
- [X] Any software project you are adding to the list is actively maintained.
- [X] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

--------------

### Why it is awesome

Kopia is a fast and secure way to backup your server, laptop.... It's easy to use either using the CLI, GUI or webUI. The compression and data deduplication helps you save a lot of space.

2022-12-11 17:10 UTC, nodiscc requested changes, later dismissed

2022-12-11 17:10 UTC, nodiscc commented on README.md
> +* [Kopia](https://kopia.io/) - Fast and encrypted incremental backups, compression and deduplication, CLI and GUI.
- [ ] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 80 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

2022-12-11 18:28 UTC, martinge17 commented
Added: Source Code, Clients, License and Language info, as requested.

2022-12-11 18:56 UTC, nodiscc commented
Thanks; this software is relatively new compared to other backup tools in the list, and has not seen a stable release yet (last release named `v0.12.1`). It's not packaged in major linux distributions yet. So if we keep going by existing contribution guidelines, this should not be included until it's more stable and mature. But contribution guidelines are not very clear, so I invite you to read https://github.com/awesome-foss/awesome-sysadmin/pull/357#issuecomment-1272604912 and further comments, and voice your opinion there.

I personally would not use this outside experimental setups yet. A backup system is an extremely critical piece of infrastructure. I did a quick ddg/reddit search on Kopia vs other backup systems and the comments I found seem to lead to the same conclusion.

2022-12-11 19:40 UTC, Technetium1 approved these changes
Looks good

2022-12-15 17:23 UTC, cu commented
I understand that the maintainers of this repo want to be cautious about adding quality software to the awesome list, and promise not to argue against a decision not to include it. But I just wanted to pop in quickly to cast my vote in support of Kopia.

I have been using Kopia for a few years now to do daily backups of various data directories and can't find anything to indicate that it is less than stable, other than the version number being <1. It's never given me any trouble at all and has saved my butt more than once. It has good docs (not that you'll need them much) and lots of active development/maintenance happening. It doesn't ship with any DEB or RPM-based Linux distro, but can be installed with native package managers via their own third-party repo. It is in the OpenBSD and FreeBSD ports trees.

If I had to pick a red flag, I would say the number of Github issues is higher than I'd like to see, but skimming through them, I feel like most of them are support requests or feature requests that the maintainers haven't bothered to close.

2022-12-20 23:50 UTC, martinge17 commented
> Thanks; this software is relatively new compared to other backup tools in the list, and has not seen a stable release yet (last release named `v0.12.1`). It's not packaged in major linux distributions yet. So if we keep going by existing contribution guidelines, this should not be included until it's more stable and mature. But contribution guidelines are not very clear, so I invite you to read [#357 (comment)](https://github.com/awesome-foss/awesome-sysadmin/pull/357#issuecomment-1272604912) and further comments, and voice your opinion there.
> 
> I personally would not use this outside experimental setups yet. A backup system is an extremely critical piece of infrastructure. I did a quick ddg/reddit search on Kopia vs other backup systems and the comments I found seem to lead to the same conclusion.

Hi, I understand the decision since it is  a young project. Anyway I would also like to hear @cu experience with Kopia.

2023-02-19 23:40 UTC, nodiscc commented
@cu @martinge17 since we're trying to update contribution guidelines/clarify _awesomeness_ criteria (https://github.com/awesome-foss/awesome-sysadmin/pull/357) can you please try to answer the following questions as best you can:

- **Have you used it? For how long?**
- **Is this in a personal or professional setup?**
- **How many devices/users/services/... do you manage with it?**
- **Biggest pros/cons compared to other solutions?**
- **Any other comments about your use case, things you've found excellent, limitations you've encountered... ?**

Thanks

2023-03-01 13:30 UTC, nodiscc commented
ping @cu @martinge17

2023-03-02 12:38 UTC, martinge17 commented
- Have you used it? For how long?

Yes, I've been using it for 4 months now.

- Is this in a personal or professional setup?

I'm using it to backup my personal Raspberry Pi 4  Homelab/NAS at home.

- How many devices/users/services/... do you manage with it?

I backup the Raspberry drive that contains Docker volumes and Syncthing folders.

- Biggest pros/cons compared to other solutions?

The most direct alternative to Kopia would, in my opinion, be Restic. Both are great pieces of software with very similar features.

**Pros of Kopia:**
    - It has a GUI client for desktop use.
    - Mount snapshots (backup) as a local folder.
    - Multiple compression algorithms.


**Cons of Kopia:**
    - Maybe it's not as mature as other solutions like Restic.


- Any other comments about your use case, things you've found excellent, limitations you've encountered... ?

I've been using Kopia for 4 months, performing regular backups a few times each week, and I haven't encountered problems. I notice that maybe they don't have as much activity in their git repository as other projects like Restic do.

2026-03-18 14:06 UTC, kokomo123 commented
Given the very old nature of this PR, should we remake another one? (sorry to bump and ping)

2026-03-18 14:26 UTC, martinge17 commented
Hi! 
I can open a new PR if needed, no problem.

2026-04-07 22:32 UTC, Technetium1 commented
@martinge17 Can't easily resolve conflicts with gui because PR was created from master branch and I don't want to rebase it or make nodiscc. In the future please create PRs from a new branch instead of the base branch. Please link to this PR in the next one.

2026-04-07 22:33 UTC, kokomo123 commented
Closing per comments above.

2026-04-07 22:33 UTC, closed without merging

2026-05-04 08:18 UTC, darkdragon-001 commented
@martinge17 could you please open a new PR? Thanks!

2026-05-04 14:07 UTC, martinge17 commented
Hi @darkdragon-001, sorry for the delay. I've just opened a new PR #787