Add NetBird to VPN
n1trux/awesome-sysadmin pull request #561
Opened 2024-03-10 19:47 UTC by ajeanselme

Thank you for taking the time to work on a PR for Awesome-Sysadmin!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software)
- [x] Software your are submitting is not your own, unless you have a healthy ecosystem with a few contributors (which aren't your sock puppet accounts).
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 80 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at [awesome-selfhosted](https://awesome-selfhosted.net)
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-foss/awesome-sysadmin/issues) or [PRs](https://github.com/awesome-foss/awesome-sysadmin/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

--------------

Please take some time to answer the following questions as best you can:

- **Why is it awesome?**

  NetBird allows to create private meshed networks very easily with a nice UI. It connects peers through Wireguard with configurable policies to enhance security.

- **Have you used it? For how long?**

I have been using it for almost a year now.

- **Is this in a personal or professional setup?**

Both. I use it to connect to my home and work networks.

- **How many devices/users/services/... do you manage with it?**

Around 50 devices.

- **Biggest pros/cons compared to other solutions?**

Pros: very easy to setup, a lot of admin control through policies, custom dns resolver to connect to peers, very active development
Cons: NetBird is still pretty early, and sometimes lack of features

- **Any other comments about your use case, things you've found excellent, limitations you've encountered... ?**

2024-05-18 11:16 UTC, Codixer commented
yes

2024-12-19 15:38 UTC, Koloblicin approved these changes
PR used and is compliant with PR template:

- software is BSD-3-clause licensed and thus 'free' under [GNU definition](https://www.gnu.org/licenses/license-list.html#ModifiedBSD)
- links, info-tags and description are correct
- title, formatting and list placement are correct
- project is active, not yet on [awesome-selfhosted](https://awesome-selfhosted.net/) and no other PRs/issues exist

Description is the company's ad slogan and could do without the part "... making it easy to create secure private networks for your organization or home." Maybe rather: ".. enabling the creation and remotre access of secure private networks."
Not a deal breaker IMO though. Thank you for your contribution.

2025-01-04 15:25 UTC, Ki-er requested changes

2025-01-04 15:25 UTC, Ki-er commented on README.md
> +- [NetBird](https://netbird.io) - NetBird combines a configuration-free peer-to-peer private network and a centralized access control system in a single platform, making it easy to create secure priv
> Docker installed on the VM with the docker-compose plugin ([Docker installation guide](https://docs.docker.com/engine/install/)) or docker with docker-compose in version 2 or higher.

```suggestion
- [NetBird](https://netbird.io) - NetBird combines a configuration-free peer-to-peer private network and a centralized access control system in a single platform, making it easy to create secure private networks for your organization or home. ([Source Code](https://github.com/netbirdio/netbird)) `BSD-3-Clause` `Docker/Go`
```

2026-03-15 23:54 UTC, kokomo123 approved these changes
After the small minor fix has been made, LGTM pending further thoughts from collaborators.

2026-04-01 13:29 UTC, Technetium1 approved these changes

2026-06-19 21:16 UTC, Rabenherz112 commented
Thanks for your contribution!

We've migrated all contributions over to a new repository: **[awesome-foss/awesome-sysadmin-data](https://github.com/awesome-foss/awesome-sysadmin-data)**. This repo no longer accepts software additions directly.

Please resubmit your software over at the new repo.

Closing this PR for now, sorry for the extra step, and thanks for understanding!

2026-06-19 21:16 UTC, closed without merging