Update README.md
n1trux/awesome-sysadmin pull request #582
Opened 2024-06-14 14:59 UTC by MISTERNEGATIVE21

Thank you for taking the time to work on a PR for Awesome-Sysadmin!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software)
- [x] Software your are submitting is not your own, unless you have a healthy ecosystem with a few contributors (which aren't your sock puppet accounts).
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 80 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at [awesome-selfhosted](https://awesome-selfhosted.net/)
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-foss/awesome-sysadmin/issues) or [PRs](https://github.com/awesome-foss/awesome-sysadmin/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

--------------

Please take some time to answer the following questions as best you can:

- **Why is it awesome?**

1Panel offers an intuitive interface for managing and monitoring servers, with real-time metrics and alerts that help maintain system health efficiently.

- **Have you used it? For how long?**

Yes, for over 2 months.

- **Is this in a personal or professional setup?**

Personal setup 

- **How many devices/users/services/... do you manage with it?**

Managing 12 services on 1 server

- **Biggest pros/cons compared to other solutions?**

**Pros:** User-friendly UI, can deploy websites , manage server resources.
**Cons:** Limited to Go language environment. 

- **Any other comments about your use case, things you've found excellent, limitations you've encountered...?**

1Panel  is just another my  server management tool  kinda like aapanel.

2024-08-07 12:54 UTC, MISTERNEGATIVE21 commented
has anyone reviewed it yet ?

2025-01-04 15:56 UTC, Ki-er requested changes

2025-01-04 15:56 UTC, Ki-er commented on README.md
> +- [1Panel](https://1panel.cn) - 🔥 🔥 🔥 Modern, open source Linux server operation and maintenance management panel. ([Source Code](https://github.com/1Panel-dev/1Panel)) `MIT` `Go`
```suggestion
- [1Panel](https://1panel.cn) - Modern Linux server operation and maintenance management panel. ([Source Code](https://github.com/1Panel-dev/1Panel)) `MIT` `Go`
```

2026-06-19 21:16 UTC, Rabenherz112 commented
Thanks for your contribution!

We've migrated all contributions over to a new repository: **[awesome-foss/awesome-sysadmin-data](https://github.com/awesome-foss/awesome-sysadmin-data)**. This repo no longer accepts software additions directly.

Please resubmit your software over at the new repo.

Closing this PR for now, sorry for the extra step, and thanks for understanding!

2026-06-19 21:16 UTC, closed without merging